### ISSUE TITLE
serialize-javascript >= 2.1.1

### ISSUE THREAD

**Issue by adibaba** [projekt-opal/web-ui#10]
Security alert: https://github.com/projekt-opal/web-ui/network/alert/package-lock.json/serialize-javascript/open

Currently:
```
"serialize-javascript": "1.4.0",
```
https://github.com/projekt-opal/web-ui/blob/master/package-lock.json

Solutions:
```
  "serialize-javascript": ">=2.1.1",
```

**Comment by mnafshin** [comment]
"serialize-javascript": {
      "version": "2.1.2",
...
}
